BLACK = (0, 0, 0)
RED = (255, 0, 0)

WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 600
WINDOW_SIZE = (WINDOW_WIDTH, WINDOW_HEIGHT)

PLAYER_WIDTH = 30
PLAYER_HEIGHT = 30
PLAYER_SIZE = (PLAYER_WIDTH, PLAYER_HEIGHT)

FPS = 60